// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountManage: typeof import('./src/components/Header/AccountManage.vue')['default']
    AdditionFee: typeof import('./src/components/Header/AdditionFee.vue')['default']
    AssetsDialog: typeof import('./src/components/AssetsDialog.vue')['default']
    AuthButton: typeof import('./src/components/AuthButton.vue')['default']
    Charts: typeof import('./src/components/Charts/index.vue')['default']
    CollapseTransition: typeof import('./src/components/CollapseTransition.vue')['default']
    CollectIcon: typeof import('./src/components/CollectIcon.vue')['default']
    ConnectWallet: typeof import('./src/components/Header/ConnectWallet.vue')['default']
    CountUp: typeof import('./src/components/CountUp.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    LeftNav: typeof import('./src/components/LeftNav.vue')['default']
    LiquiditySymbols: typeof import('./src/components/LiquiditySymbols.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PieChart: typeof import('./src/components/Charts/PieChart.vue')['default']
    SwitchChain: typeof import('./src/components/SwitchChain.vue')['default']
    SymbolIcon: typeof import('./src/components/SymbolIcon.vue')['default']
    SymbolInfo: typeof import('./src/components/SymbolInfo.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList.vue')['default']
  }
}

export { }
