const logos = {
  '5-22': 'http://nassets.oss-us-west-1.aliyuncs.com/YFI.png',
  '5-23': 'http://nassets.oss-us-west-1.aliyuncs.com/BUSD.png',
  '5-24': 'http://nassets.oss-us-west-1.aliyuncs.com/HUSD.png',
  '2-144': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-27': 'http://nassets.oss-us-west-1.aliyuncs.com/SHI.png',
  '5-80': 'http://nassets.oss-us-west-1.aliyuncs.com/TRB.png',
  '2-58': 'http://nassets.oss-us-west-1.aliyuncs.com/NABOX.png',
  '5-82': 'http://nassets.oss-us-west-1.aliyuncs.com/WETH.png',
  '5-83': 'http://nassets.oss-us-west-1.aliyuncs.com/MKR.png',
  '5-20': 'http://nassets.oss-us-west-1.aliyuncs.com/DAI.png',
  '5-87': 'http://nassets.oss-us-west-1.aliyuncs.com/DX.png',
  '2-29': 'http://nassets.oss-us-west-1.aliyuncs.com/BIG.png',
  '2-1': 'http://nassets.oss-us-west-1.aliyuncs.com/NULS.png',
  '5-1': 'http://nassets.oss-us-west-1.aliyuncs.com/NVT.png',
  '5-2': 'http://nassets.oss-us-west-1.aliyuncs.com/ETH.png',
  '5-3': 'http://nassets.oss-us-west-1.aliyuncs.com/USDX.png',
  '16-1': 'http://nassets.oss-us-west-1.aliyuncs.com/TTT.png',
  '5-6': 'http://nassets.oss-us-west-1.aliyuncs.com/HT.png',
  '5-7': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-33': 'http://nassets.oss-us-west-1.aliyuncs.com/ONE.png',
  '5-55': 'http://nassets.oss-us-west-1.aliyuncs.com/TRX.png',
  '5-77': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-8': 'http://nassets.oss-us-west-1.aliyuncs.com/BNB.png',
  '5-34': 'http://nassets.oss-us-west-1.aliyuncs.com/MATIC.png',
  '5-78': 'http://nassets.oss-us-west-1.aliyuncs.com/BNU.png',
  '5-9': 'http://nassets.oss-us-west-1.aliyuncs.com/HT.png',
  '5-12': 'http://nassets.oss-us-west-1.aliyuncs.com/OKT.png',
  '5-35': 'http://nassets.oss-us-west-1.aliyuncs.com/KCS.png',
  '5-13': 'http://nassets.oss-us-west-1.aliyuncs.com/USDX.png',
  '5-14': 'http://nassets.oss-us-west-1.aliyuncs.com/GOAT.png',
  '5-15': 'http://nassets.oss-us-west-1.aliyuncs.com/SAFEMOON.png',
  '5-16': 'http://nassets.oss-us-west-1.aliyuncs.com/GOAT.png',
  '5-17': 'http://nassets.oss-us-west-1.aliyuncs.com/LINK.png',
  '5-93': 'http://nassets.oss-us-west-1.aliyuncs.com/CRO.png',
  '5-72': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-94': 'http://nassets.oss-us-west-1.aliyuncs.com/AVAX.png',
  '5-73': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-95': 'http://nassets.oss-us-west-1.aliyuncs.com/AETH.png',
  '5-74': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-96': 'http://nassets.oss-us-west-1.aliyuncs.com/FTM.png',
  '5-32': 'http://nassets.oss-us-west-1.aliyuncs.com/TKN.png',
  '5-90': 'http://nassets.oss-us-west-1.aliyuncs.com/USDT.png',
  '5-114': 'http://nassets.oss-us-west-1.aliyuncs.com/HTN.png'
};

export default logos;
